services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-tp4
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  cli:
    image: redis:latest
    container_name: redis-tp4-cli
    depends_on:
      - redis
    entrypoint: ["redis-cli", "-h", "redis"]
    profiles:
      - cli

volumes:
  redis-data:
